const chatTestData = [
  {
    id: 1,
    username: "Cristina",
    userId: 2,
    userAvatar: null,
    text: "Hey there! I was wondering if I could borrow a lawn mower for the weekend. Do you have one available?",
    date: "Today, 5:00 PM",
  },
  {
    id: 2,
    username: "Olivia",
    userId: 1,
    userAvatar: null,
    text: "Hi Christina! Yes, I do have a lawn mower you can borrow. I’ll go ahead and arrange the deal for you right now, and don't worry, it’ll be free of charge.",
    date: "Today, 5:00 PM",
  },
  {
    id: 3,
    username: "Cristina",
    userId: 2,
    userAvatar: null,
    text: "That's amazing, thank you so much! How do I go about picking it up?",
    date: "Today, 5:00 PM",
  },
  {
    id: 4,
    username: "Olivia",
    userId: 1,
    userAvatar: null,
    text: "You're welcome! Just let me know a convenient time for you, and I'll make sure it's ready for pick up. We can finalize the details through our ToolShare app.",
    date: "Today, 5:00 PM",
  },
  {
    id: 5,
    username: "Cristina",
    userId: 2,
    userAvatar: null,
    text: "Sounds perfect. I'll send you a message in the app with the time. Thanks again!",
    date: "Today, 5:00 PM",
  },
  {
    id: 6,
    username: "Olivia",
    userId: 1,
    userAvatar: null,
    text: "No problem at all, happy to help. See you soon!",
    date: "Today, 5:00 PM",
  },
]